[build]
  command = "pnpm run build"
  publish = ".next"

[build.environment]
  NODE_ENV = "production"

# Lighthouse plugin (global)
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
    fail_deploy_on_score_thresholds = "true"
  [plugins.inputs.thresholds]
    performance        = 0.9      # 90% 
    accessibility      = 0.9      # 90% 
    seo                = 0.9      # 90% 

# Asset processing
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[build.processing.forms]
  enabled = true

# ──────────────────────────────────────────────────────────────────────────────
# Production context: security headers + Lighthouse env
# ──────────────────────────────────────────────────────────────────────────────

  [[headers]]
    for = "/*"
    [headers.values]
      X-Frame-Options         = "DENY"
      X-XSS-Protection        = "1; mode=block"
      X-Content-Type-Options  = "nosniff"
      Referrer-Policy         = "strict-origin-when-cross-origin"
      Link                    = "</images/tappy-icon.jpg>; rel=preload; as=image"

# ──────────────────────────────────────────────────────────────────────────────
# Deploy-preview context: same headers + Lighthouse env
# ──────────────────────────────────────────────────────────────────────────────
