[build]
  command = "next build"
  publish = ".next"

# Handle 404s
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com https://www.clarity.ms; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://www.google-analytics.com; connect-src 'self' https://www.google-analytics.com https://www.clarity.ms; font-src 'self'; frame-src 'self'; object-src 'none'"
    Link = "</images/tappy-icon.png>; rel=preload; as=image"

# Lighthouse CI plugin configuration
[context.production.environment]
  LIGHTHOUSE_AUDIT = "true"

[context.deploy-preview.environment]
  LIGHTHOUSE_AUDIT = "true"

# Lighthouse audit settings
[plugins.inputs.lighthouse]
  performance = 90
  accessibility = 90
  best-practices = 90
  seo = 90

# Brotli compression
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Forms handling
[build.environment]
  NODE_ENV = "production"

# Netlify form handling
[build.processing.forms]
  enabled = true
